### ISSUE TITLE
Missing 249.4 tag?

### ISSUE THREAD

**Issue by thesamesam** [systemd/systemd-stable#115]
I noticed that Fedora rawhide [currently](https://src.fedoraproject.org/rpms/systemd/c/7a99d80faaedc34baf75c864278c2871f735cfc2?branch=rawhide) has 249.4, but the last tag in this repository is 249.3.

Is 249.4 an official release?

Thanks!

**Comment by keszybz** [comment]
Oops, indeed. I pushed the tag now.

**Comment by thesamesam** [comment]
Thanks @keszybz!
