### ISSUE TITLE
Request to pull 'basic: update CIFS magic' into stable

### ISSUE THREAD

**Issue by heitbaum** [systemd/systemd-stable#166]
**Is your feature request related to a problem? Please describe.**
Hi Team,

For the next stable release could you please pull 'basic: update CIFS magic' - https://github.com/systemd/systemd/pull/22312

Could I please request that the following commit be pulled into the -stable
bbe53713455be38c0a587626439fd171f28c77fc

**Describe the solution you'd like**
Please pull this commit into the next -stable release of v250

**Comment by bluca** [comment]
https://github.com/systemd/systemd-stable/commit/e697fa60073f4359e4062a7c6b0b9f5b0edc73f9
