### ISSUE TITLE
Please create a v250 tag later than v250.8

### ISSUE THREAD

**Issue by ipilcher** [systemd/systemd-stable#233]
### systemd version the issue has been seen with

v250.8

### Used distribution

Rocky Linux 9.1

### Linux kernel version used

5.14.0-162.6.1.el9_1.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

See below.

### Unexpected behaviour you saw

I am seeing the issue described [here](https://github.com/systemd/systemd/issues/24717) on Rocky Linux 9.1, with `systemd-networkd-250.3-1.el9.x86_64` from Fedora EPEL.  [The fix for this issue](https://github.com/systemd/systemd-stable/commit/852bf93826b151be8b85d894071d95eb3b0d4498) has been committed, but no tags have been created since then.

Thus, packages like the Fedora EPEL RPM are unlikely to pick up the fix.

### Steps to reproduce the problem

See above.

**Comment by Conan-Kudo** [comment]
[CentOS Stream 9 is being upgraded to systemd 252](https://gitlab.com/redhat/centos-stream/rpms/systemd/-/merge_requests/59), so this will likely become unneeded soon.

The `systemd-extras` package in EPEL will be upgraded to systemd 252 to go along with it eventually.

**Comment by Conan-Kudo** [comment]
I've also [filed a bug on the `systemd-extras` package accordingly](https://bugzilla.redhat.com/show_bug.cgi?id=2150512).

**Comment by Conan-Kudo** [comment]
> [The fix for this issue](https://github.com/systemd/systemd-stable/commit/852bf93826b151be8b85d894071d95eb3b0d4498) has been committed, but no tags have been created since then.

That fix does not appear to be in v250-stable either, but it will be picked up with the upgrade to v252.3.

**Comment by keszybz** [comment]
Fixed by v250.9 (1d5e0e9910500f3c3584485f77bfc35e601036e3).
