### ISSUE TITLE
Backport systemd-sysext fix for 251

### ISSUE THREAD

**Issue by pothos** [systemd/systemd-stable#242]
### Component

systemd-sysext

### Is your feature request related to a problem? Please describe

Currently systemd-sysext can't load images from a `NAME.raw` symlink if the final file (which can be in any directory) doesn't also have the name `NAME.raw`. This makes it hard to use a version in the final file and let the symlink point to the wanted version.
A fix is in
https://github.com/systemd/systemd-stable/commit/e374439f4b8def786031ddbbd7dfdae3a335d4d2 (part of 252)

### Describe the solution you'd like

Backport to 251 for inclusion in the next point release

### Describe alternatives you've considered

Carry a backport in Flatcar - Edit: not a good idea, it needs other changes as well

### The systemd version you checked that didn't have the feature you are asking for

251

**Comment by pothos** [comment]
Not sure if this is a good idea in the end because it requires other changes as well from a quick look and jumping to 252 is probably the better idea? How did you normally handle such cases?

**Comment by keszybz** [comment]
Yeah, it doesn't apply cleanly and it's more of an RFE than a bugfix. If somebody wants to, please provide a backport pull request. I won't do this myself, so I'm closing this for now.

> How did you normally handle such cases?

Case by case? I really depends on what you need. But keeping up with the latest version when starting to use some new technology usually makes the most sense. There's a bazillion other fixes and featurelets that will turn out to be needed.
