### ISSUE TITLE
backport OOMPolicy fixes in v252

### ISSUE THREAD

**Issue by pennae** [systemd/systemd-stable#245]
### Component

systemd

### Is your feature request related to a problem? Please describe

v252 and v252.1 will kill an entire login session if a single process in that session is OOM-killed. this is very inconvenient and has since been changed for v253.

### Describe the solution you'd like

backport systemd/systemd#25385 and systemd/systemd#25725

### Describe alternatives you've considered

backporting the patch in each distro as mentioned in https://github.com/systemd/systemd/issues/25376#issuecomment-1355134719. this will leave at least nixos hanging on to this problem until 253 because nixos [strongly prefers to pick up patches through systemd-stable](https://github.com/NixOS/nixpkgs/pull/210687#pullrequestreview-1248759381)

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by keszybz** [comment]
Fixed by #246.
