### ISSUE TITLE
Please backport the fix for the suspend-then-hibernate regression

### ISSUE THREAD

**Issue by calumapplepie** [systemd/systemd-stable#269]
### systemd version the issue has been seen with

252.5

### Used distribution

Debain Testing

### Linux kernel version used

6.1.0-5-amd64

### CPU architectures issue was seen on

x86_64

### Component

loginctl, systemctl, other

### Expected behaviour you didn't see

Suspend-then-hibernate works as in 251 and 253, and as it is expected to work virtually all the time.

### Unexpected behaviour you saw

Suspend-then-hibernate uses a poorly documented behavior, distinct from any other systemd version, as described in https://github.com/systemd/systemd/issues/26296 .

This behavior is a regression, and the patch that fixes it (https://github.com/systemd/systemd/pull/25374/commits/4f58b656d92b09a953b7cffcfd1ee6d5136a57ed ) should really be backported to the 252 stable branch.

### Steps to reproduce the problem

systemctl suspend-then-hibernate

I am willing to aid in backporting if needed.

**Comment by mbiebl** [comment]
This is fixed in 252.6 afaics

**Comment by calumapplepie** [comment]
sorry; I had tried to locate the patch in the 252 tree, since I'd seen that 252.6 was on its way, but obviously I missed it.  Verified that the man page has the patch, and the behavior is now correct.  Thank you, and sorry again for the noise!
