### ISSUE TITLE
inet6 address is not coming up after restarting networkd

### ISSUE THREAD

**Issue by sshedi** [systemd/systemd-stable#309]
### systemd version the issue has been seen with

247.13

### Used distribution

Photon OS

### Linux kernel version used

5.10.186-1.ph4

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

Hi Systemd Devs,

```
root@ph4dev:~ # cat /etc/systemd/network/99-dhcp-en.network
[Match]
Name=e*

[Network]
LinkLocalAddressing=no
Address=<static-ip>
Gateway=...
DNS=...

[DHCPv4]
SendRelease=no
```

And as expected, there is no inet6 address.
```
root@ph4dev:~ # ifconfig
eth0  Link encap:Ethernet  HWaddr 00:0c:29:df:0e:23
          inet addr:10.197.103.175  Bcast:10.197.103.255  Mask:255.255.254.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:34676 errors:0 dropped:24 overruns:0 frame:0
          TX packets:331 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:8196459 (8.1 MB)  TX bytes:43091 (43.0 KB)
```

Next I added `DHCP=ipv6` in network file.
```
root@ph4dev:~ # cat /etc/systemd/network/99-dhcp-en.network
[Match]
Name=e*

[Network]
DHCP=ipv6
Address=...
Gateway=...
DNS=...

[DHCPv4]
SendRelease=no
```

And did `systemctl restart systemd-networkd`

```
root@ph4dev:~ # ifconfig
eth0  Link encap:Ethernet  HWaddr 00:0c:29:df:0e:23
          inet addr:10.197.103.175  Bcast:10.197.103.255  Mask:255.255.254.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:35007 errors:0 dropped:24 overruns:0 frame:0
          TX packets:357 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:8269103 (8.2 MB)  TX bytes:47635 (47.6 KB)
```

There is no inet6 address populated.

And doing:
```
networkctl reload && networkctl down eth0 && networkctl up eth0
```
populates inet6 addresses as expected.

I think I have found the fix for this issue.
https://github.com/systemd/systemd-stable/commit/77d65e5659b681209f15ca914cdc7a40e5ead48e

This went to `v251`

Hi @ius & @yuwata (sorry for spamming you),

Is it possible to port this fix to 247.x stable tree?
I tried but there are major code changes between `v251` & `v247.13`.
Or if there are any work arounds or a fix is available somewhere else, please let me know.

[networkd-debug.log](https://github.com/systemd/systemd-stable/files/12238366/networkd-debug.log)

--
sshedi

**Comment by bluca** [comment]
yes, as mentioned it is too old and we don't maintain it anymore

**Comment by sshedi** [comment]
FWIW, if anyone out there is facing this issue; I ported this fix to 247.x
https://github.com/vmware/photon/blob/4.0/SPECS/systemd/network-attempt-to-trigger-kernel-IPv6LL-address-gen.patch

This concludes this issue. Thanks.
