### ISSUE TITLE
Requirement on gcc has been bumped from 4.7 to 8 for the v254 stable tree

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd-stable#368]
### systemd version the issue has been seen with

254.9

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Regression introduced by d44fe47f2ea48fd6da83d1748ff37f46df8b4ddd (part of v254.9) where the version of gcc has been bumped which is not OK during for a stable release.

Please revert.

**Comment by keszybz** [comment]
I'll close this, because while I can symphatetize, we don't have resources to work on this. If you care enough to whip a patch, please submit a PR.
