### ISSUE TITLE
The timedatectl command times out, it seems that systemd take too long to reload service  when ntp status is changed?

### ISSUE THREAD

**Issue by jack206** [systemd/systemd-stable#380]
### systemd version the issue has been seen with

systemd 253 (253.1-5-g3e507f6)

### Used distribution

v253-stable（SRCREV = "6c327d74aa0d350482e82a247d7018559699798d"）

### Linux kernel version used

5.15.5-ebd46c8

### CPU architectures issue was seen on

None

### Component

timedatectl

### Expected behaviour you didn't see

root@BMC:~# time timedatectl set-ntp 1

real    0m0.269s
user    0m0.022s
sys     0m0.034s

### Unexpected behaviour you saw

root@BMC:~# time timedatectl set-ntp 0
Failed to set ntp: Connection timed out

real    0m25.099s
user    0m0.024s
sys     0m0.037s
root@BMC:~# time timedatectl set-ntp 1
Failed to set ntp: Connection timed out

real    0m25.099s
user    0m0.050s
sys     0m0.012s

### Steps to reproduce the problem

 timedatectl set-ntp 0 or timedatectl set-ntp 1

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
na
```

**Comment by yuwata** [comment]
This is a repository for managing stable releases. Please first try to reproduce the issue with the upstream (https://github.com/systemd/systemd) git HEAD. If it is reproducible with the upstream, then open an issue page there with debugging logs. If cannot, please try to find which commit fixes the issue, and request to backport the fix.
Closing.
