### ISSUE TITLE
Any chance to backport #32224  to V255?

### ISSUE THREAD

**Issue by Cody-Learner** [systemd/systemd-stable#391]
### systemd version in use
Arch testing repo versions:
`systemd 255.5-2`
`systemd-libs 255.5-2`

### Used distribution

Arch

### CPU architectures issue was seen on

x86_64

### Component

systemd-vmspawn

### Is your feature request related to a problem? Please describe

$ mkosi -d arch -p systemd -p linux --autologin -o image.raw -f build
$ systemd-vmspawn --image=image.raw

Running: `systemd-vmspawn --image=image.raw` results in the following error:

`Using vsock-stream:2:118463064`
`systemd-vmspawn error    !!!! IA32 Exception Type - 0E(#PF - Page-Fault)  CPU Apic ID - 00000000 !!!!`
`....`

### Describe the solution you'd like

Seems there is a fix that was applied to the 256 version.  https://github.com/systemd/systemd/pull/32224

I'd be cool to see the fix applied to 255 if possible, not taking into account when 256 may be available in the Arch testing repos.

### Describe alternatives you've considered

Waiting for 256 to hit Arch testing would be the alternative.

### The systemd version you checked that didn't have the feature you are asking for

255.5-2

**Comment by Cody-Learner** [comment]
I installed the AUR systemd-git package that provided the following packages:

`systemd-git meson.version.r73257.132f6cfcfe-1`
`systemd-libs-git meson.version.r73257.132f6cfcfe-1`
`systemd-resolvconf-git meson.version.r73257.132f6cfcfe-1`
`systemd-sysvcompat-git meson.version.r73257.132f6cfcfe-1`
`systemd-ukify-git meson.version.r73257.132f6cfcfe-1`

Now `systemd-vmspawn` works for the Arch image I had created earlier, however there are other issues. 
1) I cannot create new images using `mkosi` due to the systemd-git package menson versions , ie:

`$ mkosi -d arch -p systemd -p linux,base,base-devel,nano,wget,sudo,git --autologin -o image.raw -f build`
‣ Syncing package manager metadata for default image
:: Synchronizing package databases...
 core                                      123.7 KiB  53.2 KiB/s 00:02 [########################################] 100%
 extra                                       7.8 MiB  1166 KiB/s 00:07 [########################################] 100%
‣ Building default image
‣ Found '/usr/bin/systemd-repart' with version meson.version.r73257.132f6cfcfe-1-arch-g132f6cf^ but version 254 or newer is required to build disk images.
‣ (Use ToolsTree=default to get a newer version of 'systemd-repart'.)

2) I had to remove `mkinitcpio` to facilitate the install: 
`:: systemd-git-meson.version.r73257.132f6cfcfe-1 and mkinitcpio-38.1-1 are in conflict (systemd). Remove mkinitcpio ? [y/N] y`

The #2 issue caused me to preinstall 'dracut' to AFAIK, satisfy an initramfs generating tool dependency for/from the linux kernel.

I prefer to stay with `mkinitcpio`, so will be reverting back to the testing versions of systemd after this brief test. Unfortunately, due to these issues the AUR systemd-git packages aren't a viable option for me.

**Comment by keszybz** [comment]
Unfortunately that patch doesn't apply cleanly, there were a bunch of reworks before it. I'd be happy to take a pull request, but I don't plan to backport it myself.

**Comment by klausenbusk** [comment]
I think it make sense to close this issue, as v256 has landed in Arch Linux with the mentioned fix.
