### ISSUE TITLE
Request for backport of systemd/systemd#31827

### ISSUE THREAD

**Issue by Nardol** [systemd/systemd-stable#404]
### Component

systemd-resolved

### Is your feature request related to a problem? Please describe

A ping to a signed domain take about 10-20 seconds when dnssec is enabled, issue systemd/systemd#31826

### Describe the solution you'd like

systemd/systemd#31827 should fix this issue if I understood correctly. On Debian 12 proposed-updates (SystemD 252.24) I have to disable DNSSec to avoid ping to reply after a so long delay.

### Describe alternatives you've considered

Disabling DNSSec is the only alternative I know

**Comment by bluca** [comment]
This PR was already backported and is already part of v252.24
