### ISSUE TITLE
Could systemd 256.1 be added to this repo

### ISSUE THREAD

**Issue by heitbaum** [systemd/systemd-stable#414]
### systemd version the issue has been seen with

256

### Used distribution

LibreELEC 13

### Linux kernel version used

kernel-6.9.5

### CPU architectures issue was seen on

x86_64

### Component

other

**Comment by eworm-de** [comment]
See https://github.com/systemd/systemd/commit/40d637bace4041f081088673cb230669c1e34faf ...

**Comment by heitbaum** [comment]
Thanks - I’ll move our CI/CD
