### ISSUE TITLE
Tagging stable branches periodically as point releases

### ISSUE THREAD

**Issue by jameshilliard** [systemd/systemd-stable#65]
To simplify updates for downstream projects using systemd it seems like it may be a good idea to periodically tag point releases off of the various stable branches, that way it would be easier for downstream projects to track security and other bug fixes using tags.

**Comment by keszybz** [comment]
I generally push stable backports in batches — by going over the master branch and selecting anything that seems appropriate. I *could* tag this, but generally, every commit on the stable branch is equally important. Would such "random" tags be still useful?

**Comment by jameshilliard** [comment]
> Would such "random" tags be still useful?

Yes I think they would be quite useful, especially for things like CVE tracking where you can have multiple point releases(for the various systemd branches) marked as having the issue "fixed" and so that distributions that prefer to follow stable upstream releases without bumping the major version or going off of git commits directly can update by simply bumping to the latest tagged point release. Even if there are many tags like say a "v243.35" stable release it makes it easier for downstream projects to track backported fixes.

**Comment by eworm-de** [comment]
I would like to see tags in stable branches in case they are signed.

**Comment by keszybz** [comment]
What should the first tag be? '243.1' or '243.90' to not conflict with arch (https://www.archlinux.org/packages/core/x86_64/systemd) or something else?

**Comment by boucman** [comment]
I'm fine with either, i'll let the people from the distros comment...

**Comment by keszybz** [comment]
I decided to "back-tag" the previous batches, so we now have v243.1, v243.2, v243.3, v243.4. The next one will be v243.5.

**Comment by boucman** [comment]
Awesome, i'll update buildroot accordingly

**Comment by eworm-de** [comment]
Thanks a lot!
For Arch this is just a minor temporary issue. Starting with v244 we will follow the new versioning.
