### ISSUE TITLE
tag release v245.9 for bug fixes

### ISSUE THREAD

**Issue by dongsupark** [systemd/systemd-stable#78]
Flatcar Linux Stable v2605.8.0 was [released](https://www.flatcar-linux.org/releases/#release-2605.8.0) with systemd v245.8.
During the release process, however, we discovered that several commits in the v245-stable branch were not included in systemd v245.8:
https://github.com/systemd/systemd-stable/commit/261680bc0ea61777ac22ea1c42b0d728ec52ae14
https://github.com/systemd/systemd-stable/commit/b2b382820bcfc166d048b85aadd90f5cf71c7a4a
https://github.com/systemd/systemd-stable/commit/711ca814c9f2e81d3d25ebbed0b837b7d4fbbeda
Especially the last commit, `core: fix securebits setting` was required. Without the fix, the system had boot issues.
So we had to manually added the fixes into systemd in Flatcar.

It would be really great, if a new release v245.9 would be tagged, including the commits above.

Thanks in advance.

**Comment by keszybz** [comment]
v245.9 is tagged now.

**Comment by dongsupark** [comment]
Thanks! :+1:
