### ISSUE TITLE
v246-stable: please backport 0e686feaff71465e3220f234871f66a39f0f57ad

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd-stable#81]
https://github.com/systemd/systemd/issues/17931 is already fixed in upstream.
The relevant fix is cabe57119f07a9f86ab281f6260bbb006b89a854 and 0e686feaff71465e3220f234871f66a39f0f57ad.
cabe57119f07a9f86ab281f6260bbb006b89a854 is already backported.
So, please also cherry-pick 0e686feaff71465e3220f234871f66a39f0f57ad.

**Comment by keszybz** [comment]
v246.8.

**Comment by yuwata** [comment]
Thank you!
